version: "1"

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gocyclo
    - gosec
    - goimports
    - revive
    - whitespace

run:
  timeout: 5m
  tests: true 